version: '3.8'

services:
  suvenirscl:
    image: mongo:7.0
    container_name: suvenirscl
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: suvenirs
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - suvenirs-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  suvenirs-network:
    driver: bridge
